assign0818/config/routes.rb
Rails.application.routes.draw do
  resources :pet_records

  resources :appointments

  resources :doctors

end

assign0818/app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :pet_record
  validates :date_of_visit , {presence: true}
  validates :customer 
  
  
end

assign0818/app/models/doctor.rb
class Doctor < ActiveRecord::Base
	has_many :appointments
	validates :name , length: {in: 1..35}
	validates :zip , length: {is: 6}
     
end

assign0818/app/models/pet_record.rb
class PetRecord < ActiveRecord::Base
	has_many :appointments
end

assign0818/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

assign0818/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:date_of_visit, :customer, :reminder, :reason, :doctor_id, :pet_record_id)
    end
end

assign0818/app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:name, :adress, :city, :state, :zip, :school, :experience)
    end
end

assign0818/app/controllers/pet_records_controller.rb
class PetRecordsController < ApplicationController
  before_action :set_pet_record, only: [:show, :edit, :update, :destroy]

  # GET /pet_records
  # GET /pet_records.json
  def index
    @pet_records = PetRecord.all
  end

  # GET /pet_records/1
  # GET /pet_records/1.json
  def show
  end

  # GET /pet_records/new
  def new
    @pet_record = PetRecord.new
  end

  # GET /pet_records/1/edit
  def edit
  end

  # POST /pet_records
  # POST /pet_records.json
  def create
    @pet_record = PetRecord.new(pet_record_params)

    respond_to do |format|
      if @pet_record.save
        format.html { redirect_to @pet_record, notice: 'Pet record was successfully created.' }
        format.json { render :show, status: :created, location: @pet_record }
      else
        format.html { render :new }
        format.json { render json: @pet_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pet_records/1
  # PATCH/PUT /pet_records/1.json
  def update
    respond_to do |format|
      if @pet_record.update(pet_record_params)
        format.html { redirect_to @pet_record, notice: 'Pet record was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet_record }
      else
        format.html { render :edit }
        format.json { render json: @pet_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pet_records/1
  # DELETE /pet_records/1.json
  def destroy
    @pet_record.destroy
    respond_to do |format|
      format.html { redirect_to pet_records_url, notice: 'Pet record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet_record
      @pet_record = PetRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_record_params
      params.require(:pet_record).permit(:pet_type, :breed, :age, :weight, :date_last_visit)
    end
end

assign0818/app/helpers/application_helper.rb
module ApplicationHelper
end

assign0818/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

assign0818/app/helpers/doctors_helper.rb
module DoctorsHelper
end

assign0818/app/helpers/pet_records_helper.rb
module PetRecordsHelper
end

assign0818/app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_of_visit %><br>
    <%= f.text_field :date_of_visit %>
  </div>
  <div class="field">
    <%= f.label :customer %><br>
    <%= f.text_field :customer %>
  </div>
  <div class="field">
    <%= f.label :reminder %><br>
    <%= f.text_field :reminder %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_field :reason %>
  </div>
  <div class="field">
    <%= f.label :doctor_id %><br>
    <%= f.text_field :doctor_id %>
  </div>
  <div class="field">
    <%= f.label :pet_record_id %><br>
    <%= f.text_field :pet_record_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

assign0818/app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

assign0818/app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<table>
  <thead>
    <tr>
     
      <th>Date of visit</th>
      <th>Customer</th>
      <th>Reminder</th>
      <th>Reason</th>
      <th>Doctor</th>
      <th>Pet record</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        
        <td><%= appointment.date_of_visit %></td>
        <td><%= appointment.customer %></td>
        <td><%= appointment.reminder %></td>
        <td><%= appointment.reason %></td>
        <td><%= appointment.doctor %></td>
        <td><%= appointment.pet_record %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

assign0818/app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

assign0818/app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date of visit:</strong>
  <%= @appointment.date_of_visit %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @appointment.customer %>
</p>

<p>
  <strong>Reminder:</strong>
  <%= @appointment.reminder %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @appointment.reason %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @appointment.doctor %>
</p>

<p>
  <strong>Pet record:</strong>
  <%= @appointment.pet_record %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

assign0818/app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :adress %><br>
    <%= f.text_field :adress %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :school %><br>
    <%= f.text_field :school %>
  </div>
  <div class="field">
    <%= f.label :experience %><br>
    <%= f.text_field :experience %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

assign0818/app/views/doctors/edit.html.erb
<h1>Editing doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

assign0818/app/views/doctors/index.html.erb
<h1>Listing doctors</h1>

<table>
  <thead>
    <tr>
     
      <th>Name</th>
      <th>Adress</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>School</th>
      <th>Experience</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.adress %></td>
        <td><%= doctor.city %></td>
        <td><%= doctor.state %></td>
        <td><%= doctor.zip %></td>
        <td><%= doctor.school %></td>
        <td><%= doctor.experience %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

assign0818/app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

assign0818/app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @doctor.adress %>
</p>

<p>
  <strong>City:</strong>
  <%= @doctor.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @doctor.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @doctor.zip %>
</p>

<p>
  <strong>School:</strong>
  <%= @doctor.school %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @doctor.experience %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

assign0818/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assign0818</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

assign0818/app/views/pet_records/_form.html.erb
<%= form_for(@pet_record) do |f| %>
  <% if @pet_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet_record.errors.count, "error") %> prohibited this pet_record from being saved:</h2>

      <ul>
      <% @pet_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pet_type %><br>
    <%= f.text_field :pet_type %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :date_last_visit %><br>
    <%= f.text_field :date_last_visit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

assign0818/app/views/pet_records/edit.html.erb
<h1>Editing pet_record</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet_record %> |
<%= link_to 'Back', pet_records_path %>

assign0818/app/views/pet_records/index.html.erb
<h1>Listing pet_records</h1>

<table>
  <thead>
    <tr>
      
      <th>Pet type</th>
      <th>Breed</th>
      <th>Age</th>
      <th>Weight</th>
      <th>Date last visit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pet_records.each do |pet_record| %>
      <tr>
      
        <td><%= pet_record.pet_type %></td>
        <td><%= pet_record.breed %></td>
        <td><%= pet_record.age %></td>
        <td><%= pet_record.weight %></td>
        <td><%= pet_record.date_last_visit %></td>
        <td><%= link_to 'Show', pet_record %></td>
        <td><%= link_to 'Edit', edit_pet_record_path(pet_record) %></td>
        <td><%= link_to 'Destroy', pet_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet record', new_pet_record_path %>

assign0818/app/views/pet_records/new.html.erb
<h1>New pet_record</h1>

<%= render 'form' %>

<%= link_to 'Back', pet_records_path %>

assign0818/app/views/pet_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pet type:</strong>
  <%= @pet_record.pet_type %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet_record.breed %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet_record.age %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @pet_record.weight %>
</p>

<p>
  <strong>Date last visit:</strong>
  <%= @pet_record.date_last_visit %>
</p>

<%= link_to 'Edit', edit_pet_record_path(@pet_record) %> |
<%= link_to 'Back', pet_records_path %>